Feature/apply standard js before commit
blueinkhq/blueink-client-js pull request #19
Opened 2023-11-22 06:05 UTC by baodoanblueink

2023-11-22 07:34 UTC, trungthanhtong requested changes
Please see comments. 
We also need to change the names of `PersonHelper.js` and `RequestHelper.js` to `personHelper.js` and `requestHelper.js` for consistent

2023-11-22 07:34 UTC, trungthanhtong commented on src/blueink/subclients/person.js
> +    },
Change `asDict` to `asData`

2023-11-22 07:34 UTC, trungthanhtong commented on src/example/create_bundle_from_b64.js
> +const fetch = require('node-fetch')
Sort imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/example/interact_persons.js
> +const { Client, PersonHelper } = require('../../index')
Reorder imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/example/create_bundle_from_url.js
> +const chalk = require('chalk')
Reorder imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/example/create_bundle_from_template.js
> +const inquirer = require('inquirer')
Reorder imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/example/create_bundle_from_path.js
> +const chalk = require('chalk')
Reorder imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/example/interact_webhooks.js
> +const { EVENT_TYPE } = require('../blueink/constants.js')
Reorder imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/example/list_bundles.js
> +const { Client } = require('../../index')
Reorder imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/test/bundle.test.js
> +const { Client } = require('../../index.js')
Imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/test/pagination.test.js
> +const { Client } = require('../../index')
Imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/test/person.test.js
> +const { Client } = require('../../index')
Imports

2023-11-22 07:34 UTC, trungthanhtong commented on src/test/template.test.js
> +const { Client } = require('../../index')
Imports

2023-11-22 07:59 UTC, geogredoansg commented on src/blueink/helper/PersonHelper.js
>    }
In this case, it is no need to define the additionalData as a function parameter, right?

2023-11-25 04:17 UTC, trungthanhtong requested changes
Please see comments

2023-11-25 04:17 UTC, trungthanhtong commented on src/blueink/helper/bundleHelper.js
> +const { FIELD_KIND } = require('../constants.js')
Please move constant above util

2023-11-25 04:17 UTC, trungthanhtong commented on src/example/create_bundle_from_b64.js
> +const inquirer = require('inquirer')
Reorder imports

2024-01-06 06:32 UTC, zlove commented
This is included in https://github.com/blueinkhq/blueink-client-js/pull/22

2024-01-06 06:32 UTC, closed without merging